# Site settings
email: "email@jimmykamau.info"
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics:

# SEO settings
title: "Jimmy Kamau"
description:
url: ""
twitter_username:
default_img:

# Profile settings
name: "Jimmy Kamau"
profile_img: "/assets/images/me.jpg"
profile: "Hi! I am Jimmy - yes, I have a hand. I eat, sleep and breathe technology."
social:
  github: "https://github.com/jimmykamau"
  twitter: "https://twitter.com/kamau_jimmy"
  facebook: "https://www.facebook.com/xerxes.slim"
  linkedin: "https://www.linkedin.com/in/jimmy-kamau"
  instagram: "https://www.instagram.com/kamaujimmy/"

# Build settings
include: ["_categories"]
exclude: ["_screenshots", "Gemfile", "Gemfile.lock"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
